import sys
from pathlib import Path

# Add current folder to sys.path
current_dir = Path(__file__).parent
if str(current_dir) not in sys.path:
    sys.path.insert(0, str(current_dir))

from .image_to_prompt import NODE_CLASS_MAPPINGS as IMAGE_TO_PROMPT_MAPPINGS
from .image_to_prompt import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_TO_PROMPT_DISPLAY_NAMES
from .switch_case import NODE_CLASS_MAPPINGS as SWITCH_CASE_MAPPINGS
from .switch_case import NODE_DISPLAY_NAME_MAPPINGS as SWITCH_CASE_DISPLAY_NAMES
from .text_lines import NODE_CLASS_MAPPINGS as TEXT_LINES_MAPPINGS
from .text_lines import NODE_DISPLAY_NAME_MAPPINGS as TEXT_LINES_DISPLAY_NAMES
from .auto_reset_int import NODE_CLASS_MAPPINGS as AUTO_RESET_INT_MAPPINGS
from .auto_reset_int import NODE_DISPLAY_NAME_MAPPINGS as AUTO_RESET_INT_DISPLAY_NAMES
from .save_image_advanced import NODE_CLASS_MAPPINGS as SAVE_IMAGE_ADVANCED_MAPPINGS
from .save_image_advanced import NODE_DISPLAY_NAME_MAPPINGS as SAVE_IMAGE_ADVANCED_DISPLAY_NAMES
from .cartesian_product import NODE_CLASS_MAPPINGS as CARTESIAN_PRODUCT_MAPPINGS
from .cartesian_product import NODE_DISPLAY_NAME_MAPPINGS as CARTESIAN_PRODUCT_DISPLAY_NAMES
from .concatenate_text_3 import NODE_CLASS_MAPPINGS as CONCATENATE_TEXT_3_MAPPINGS
from .concatenate_text_3 import NODE_DISPLAY_NAME_MAPPINGS as CONCATENATE_TEXT_3_DISPLAY_NAMES

NODE_CLASS_MAPPINGS = {
    **IMAGE_TO_PROMPT_MAPPINGS,
    **SWITCH_CASE_MAPPINGS,
    **TEXT_LINES_MAPPINGS,
    **AUTO_RESET_INT_MAPPINGS,
    **SAVE_IMAGE_ADVANCED_MAPPINGS,
    **CARTESIAN_PRODUCT_MAPPINGS,
    **CONCATENATE_TEXT_3_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_TO_PROMPT_DISPLAY_NAMES,
    **SWITCH_CASE_DISPLAY_NAMES,
    **TEXT_LINES_DISPLAY_NAMES,
    **AUTO_RESET_INT_DISPLAY_NAMES,
    **SAVE_IMAGE_ADVANCED_DISPLAY_NAMES,
    **CARTESIAN_PRODUCT_DISPLAY_NAMES,
    **CONCATENATE_TEXT_3_DISPLAY_NAMES,
}

# Export JS directory for frontend extensions
WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
